# Generated by Django 5.1.7 on 2026-09-13 06:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Smartphone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smartphones",
                        to="smartphones.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smartphone",
                "verbose_name_plural": "Smartphones",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "smartphone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="smartphones.smartphone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartphoneSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ram", models.PositiveIntegerField(help_text="GB")),
                ("storage", models.PositiveIntegerField(help_text="GB")),
                ("battery", models.PositiveIntegerField(help_text="mAh")),
                ("camera", models.PositiveIntegerField(help_text="Megapixel")),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("LCD", "LCD"),
                            ("IPS", "IPS"),
                            ("OLED", "OLED"),
                            ("AMOLED", "AMOLED"),
                        ],
                        max_length=10,
                    ),
                ),
                ("processor", models.CharField(max_length=100)),
                ("weight", models.PositiveIntegerField(help_text="Gram")),
                (
                    "smartphone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification",
                        to="smartphones.smartphone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smartphone Specification",
                "verbose_name_plural": "Smartphone Specifications",
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("max_price", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "camera_weight",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "battery_weight",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "performance_weight",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "display_weight",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_users",
                        to="smartphones.brand",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.AddIndex(
            model_name="smartphone",
            index=models.Index(fields=["name"], name="smartphones_name_558c78_idx"),
        ),
        migrations.AddIndex(
            model_name="smartphone",
            index=models.Index(fields=["brand"], name="smartphones_brand_i_6d26f0_idx"),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["smartphone", "-created_at"],
                name="smartphones_smartph_74c00c_idx",
            ),
        ),
    ]
