# Generated by Django 5.1.7 on 2026-09-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Chipset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "antutu_score",
                    models.PositiveIntegerField(help_text="AnTuTu v10 benchmark score"),
                ),
                ("geekbench_multi", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Chipset",
                "verbose_name_plural": "Chipsets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Smartphone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("ram_gb", models.PositiveSmallIntegerField()),
                ("storage_gb", models.PositiveIntegerField()),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("emmc", "eMMC"),
                            ("ufs2_2", "UFS 2.2"),
                            ("ufs3_1", "UFS 3.1"),
                            ("ufs4_0", "UFS 4.0"),
                        ],
                        max_length=20,
                    ),
                ),
                ("battery_mah", models.PositiveIntegerField()),
                ("fast_charging_w", models.PositiveIntegerField(default=0)),
                ("display_refresh_hz", models.PositiveSmallIntegerField()),
                ("display_ppi", models.PositiveIntegerField()),
                ("main_camera_mp", models.PositiveIntegerField()),
                ("has_ois", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smartphones",
                        to="smartphones.brand",
                    ),
                ),
                (
                    "chipset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smartphones",
                        to="smartphones.chipset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smartphone",
                "verbose_name_plural": "Smartphones",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "smartphone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="smartphones.smartphone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="smartphone",
            index=models.Index(fields=["name"], name="smartphones_name_558c78_idx"),
        ),
        migrations.AddIndex(
            model_name="smartphone",
            index=models.Index(fields=["brand"], name="smartphones_brand_i_6d26f0_idx"),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["smartphone", "-created_at"],
                name="smartphones_smartph_74c00c_idx",
            ),
        ),
    ]
