# Generated by Django 5.1.7 on 2026-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartphones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartphone",
            name="display_type",
            field=models.CharField(
                choices=[
                    ("OLED", "OLED"),
                    ("IPS", "IPS"),
                    ("LCD", "LCD"),
                    ("AMOLED", "AMOLED"),
                ],
                default="AMOLD",
                max_length=10,
            ),
        ),
    ]
