# Generated by Django 5.1.7 on 2026-09-19 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smartphones", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPreference",
        ),
    ]
