# Generated by Django 5.1.7 on 2026-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartphones", "0004_alter_smartphone_display_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smartphone",
            name="has_ois",
        ),
        migrations.AddField(
            model_name="smartphone",
            name="battery_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="camera_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="display_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="smartphone",
            name="performance_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name="smartphone",
            index=models.Index(
                fields=["performance_score"], name="smartphones_perform_595670_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smartphone",
            index=models.Index(
                fields=["camera_score"], name="smartphones_camera__badf33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smartphone",
            index=models.Index(
                fields=["display_score"], name="smartphones_display_8f65a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smartphone",
            index=models.Index(
                fields=["battery_score"], name="smartphones_battery_fc7d13_idx"
            ),
        ),
    ]
