# Generated by Django 5.1.7 on 2026-09-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "smartphones",
            "0005_remove_smartphone_has_ois_smartphone_battery_score_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="smartphone",
            name="technolife_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="smartphone",
            name="battery_mah",
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
