# Generated by Django 5.1.7 on 2026-09-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartphones", "0006_smartphone_technolife_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartphone",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
